# GENERATED - do not edit unless you know what you're doing
set(MYPROJECT_SOURCES
  src/main.cpp
  src/core/base/GameObject.cpp
  src/core/base/Item.cpp
  src/core/character/Hireling.cpp
  src/core/character/Monster.cpp
  src/core/character/NPC.cpp
  src/core/character/PlayableCharacter.cpp
  src/core/character/Villager.cpp
  src/core/item/ConsummableItem.cpp
  src/core/item/NonConsummableItem.cpp
  src/core/item/QuestItem.cpp
  src/core/item/WearableItem.cpp
  src/core/world/MapArea.cpp
  src/core/world/Waypoint.cpp
  src/utils/GameEnv.cpp
  src/utils/LootGenerator.cpp
  src/utils/MapGenerator.cpp
  src/utils/MobGenerator.cpp
  src/utils/UuidV7.cpp
)
